### ISSUE TITLE
Add ways to test non-process code

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio-cli#14]
As a component developer, I want to test verify credentials and functions that generate in metadata and dynamic dropdowns.

**Comment by hannah-bulmer** [comment]
The latter (generating in metadata and dynamic dropdowns, etc) actually already exists! It is in a pre-existing command called `cmp: exec` which can be renamed

**Comment by hannah-bulmer** [comment]
Solved in https://github.com/elasticio/elasticio-cli/pull/24
