### ISSUE TITLE
Add Utility to Assert Component Validity

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio-cli#15]
There are lots of subtile errors that can be made in component.json or the construction of code files that would cause strange behavior on the platform.  We should do checks for such errors in an automated way.

- Check component.json for validity
    - valid JSON, options are valid (e.g. viewClasses, etc)
- Check each code file
  - ensure each one exists and has a process function exported
- Check static schemas for validity
  - using integer, unable to parse, etc

**Comment by hannah-bulmer** [comment]
- [ ] assert component.json is valid JSON
- [ ] assert component.json contains valid fields and options
- [ ] assert every path for actions/triggers is valid
- [ ] assert static schemas are all valid
- [ ] more details on valid schemas

**Comment by hannah-bulmer** [comment]
Completed in https://github.com/elasticio/elasticio-cli/pull/22
