### ISSUE TITLE
Update README and error messages

### ISSUE THREAD

**Issue by hannah-bulmer** [elasticio/elasticio-cli#26]
The README for this tool is a little bit confusing. A better way to display information would be to sort it by each available command in the tool.

I would propose the following README sections:

- installation
- creating test fixtures
- cmp:process
  - flags
  - exactly what it does
  - examples and expected output
  - limitations
- cmp:exec
  - flags
  - exactly what it does
  - examples and expected output
  - limitations
- cmp:validate
  - flags
  - exactly what it does
  - examples and expected output
  - limitations

I also see that `cmp:process` and `cmp:exec` are fairly similar; are they worth merging into one tool or are there benefits of keeping them separate?

Furthermore, I would propose refining the current CLI output and making it more user-friendly, readable, and useful to a user.

**Comment by hannah-bulmer** [comment]
@dvd-z @jhorbulyk thoughts?

**Comment by dvd-z** [comment]
looks good

**Comment by hannah-bulmer** [comment]
@dvd-z what is your thought on merging `cmp:process` and `cmp:exec` or keeping them as seperate tools?

Both currently run `process` functions, `cmp:exec` allows you to run other exported functions like `getMetaModel` and `verifyCredentials`. It does not run `init` and `startup` and `shutdown` along with `process` though.

Perhaps a better thing to do would be to rename the commands to be more intuitive? `exec` is rather vague...

**Comment by dvd-z** [comment]
I feel like there should definitely be a big command that'll run `init`, `startup`, `process`, and `shutdown`. It would be nice if it were with exec just to keep everything together, but I don't know how that would be cleared specified to the user

**Comment by hannah-bulmer** [comment]
Excuted in https://github.com/elasticio/elasticio-cli/pull/32
