### ISSUE TITLE
Run component code in a node vm context

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio-cli#31]
See https://nodejs.org/api/vm.html and https://github.com/elasticio/code-component/blob/master/actions/code.js for some context.

Biggest benefit may be ability to isolate stack traces to only include component code.

**Comment by dvd-z** [comment]
`process.js` now uses `vm`. `exec.js` still needs to be converted.

**Comment by jhorbulyk** [comment]
It probably doens't make sense to do this at the moment.  The big problem with using VM at the moment is that by default, IDE debuggers (e.g. Webstorm, VS Code) do not step into VM code and one of the common use cases of the tool ist to act as a launch configuration for IDEs.
