### ISSUE TITLE
reactivate command line interface

### ISSUE THREAD

**Issue by juhrmacher** [elasticio/elasticio-cli#5]
User story:

- As a component developer, I want to have my component's process function run outside the platform given a set of input values.
    - Incoming message, config and snapshot should be set to input values
    - All emitted values (of all supported types) should be recorded
    - All environment variables should be set
    - The emit function should be defined and return a promise.
    - Overlapping emits calls should be detected and not allowed.
    - Logger should be defined and log statements collected.
    - Steward (Attachment API) should be mocked and reading/storing attachments should be simulated.
    - Startup/Shutdown and Init functions should be called as expected.
    - Any OAuth keys to be provided for my execution run.
- As a component developer, I want to test verify credentials and functions that generate in metadata and dynamic dropdowns.
- As a component developer, I want to make sure that the test inputs match with what is described in component.json/input schemas
    - I want to make sure the rules of my schemas can be rendered on the platform and validate the rules of allowed data.
    - I want any errors based on the structure of component.json to be caught automatically.

**Comment by jhorbulyk** [comment]
Mostly completed.
